import { chromium } from 'playwright'

const out = process.argv[2]
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1200, height: 700 }, deviceScaleFactor: 1 })
const errors = []
page.on('pageerror', (e) => errors.push(e.message))
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()) })
await page.goto('http://localhost:5199/', { waitUntil: 'networkidle' })
await page.waitForTimeout(500)
const shot = async (name) => page.screenshot({ path: `${out}/${name}.png` })

await shot('01-rooms')
await page.click('.rl-row >> nth=0')
await page.waitForTimeout(150)
await shot('02-room-open')
await page.click('.ps-thumb >> nth=1')
await page.waitForTimeout(150)
await shot('03-lightbox')
await page.click('.lb-close')
await page.click('.rl-view >> nth=0')
await page.waitForTimeout(600)
await shot('04-profile')
await page.click('.ar-tab >> text=Shared Facilities')
await page.click('.rl-row >> nth=0')
await shot('05-facilities')
await page.click('.ar-tab >> text=Permits')
await shot('06-permits')
await page.click('.pm-view >> nth=1')
await page.waitForTimeout(600)
await shot('07-permit-viewer')
await page.click('.pv-close')
await page.click('.ar-tab >> text=Activity')
await shot('08-activity')
await page.click('.ar-tab >> text=Reviews')
await shot('09-reviews')
await page.click('.ov-dots')
await shot('10-menu')
console.log(errors.length ? 'ERRORS:\n' + errors.join('\n') : 'no page errors')
await browser.close()
