import js from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import pluginVue from 'eslint-plugin-vue'

// Deliberately close to the code that already exists rather than to any
// published style guide. The point is to catch the classes of mistake this
// codebase has actually shipped — unused bindings left behind by a refactor,
// `as any` papering over a type, floating promises — not to restyle 20k lines.
//
// Formatting rules are left off entirely: there is no Prettier here, and a
// formatting sweep would bury real findings in whitespace noise.
export default tseslint.config(
  {
    ignores: [
      'dist/**',
      '.quasar/**',
      'node_modules/**',
      'src/types/database.gen.ts', // generated by the Supabase CLI
      'quasar.config.*.temporary.compiled*',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...pluginVue.configs['flat/recommended'],
  {
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
      parserOptions: {
        parser: tseslint.parser,
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
    },
    rules: {
      // Caught the dead `lastRejected` in the router and the four unused
      // exports in boot/notify.ts. Underscore-prefixed args stay allowed —
      // upload.ts uses them for kept-for-parity parameters.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // Warn, not error: the drawer and table code leans on `any` in places
      // where the Supabase generated types genuinely do not line up yet.
      // Visible without blocking a commit.
      '@typescript-eslint/no-explicit-any': 'warn',

      // Vue's recommended set is heavy on formatting and attribute ordering.
      // Off — see the note above.
      'vue/max-attributes-per-line': 'off',
      'vue/singleline-html-element-content-newline': 'off',
      'vue/html-self-closing': 'off',
      'vue/html-indent': 'off',
      'vue/html-closing-bracket-newline': 'off',
      'vue/attributes-order': 'off',
      'vue/first-attribute-linebreak': 'off',
      // Page components are legitimately named Dashboard, Users, Settings.
      'vue/multi-word-component-names': 'off',
    },
  },
  {
    files: ['**/*.test.ts'],
    languageOptions: { globals: { ...globals.node } },
  },
)
